### ISSUE TITLE
Error around playing sounds with sheepy

### ISSUE THREAD

**Issue by ketzu** [Ma-Ko-dev/Sheepy#2]
Running sheepy I encounter an error after the first exit. I installed playsound but nothing else and ran sheepy via `python .\main.py` on windows 10.

```
    Error 263 for command:
        open sfx/sheep_noise.mp3
    Gerät ist nicht geöffnet oder wird vom MCI nicht erkannt.

    Error 263 for command:
        close sfx/sheep_noise.mp3
    Gerät ist nicht geöffnet oder wird vom MCI nicht erkannt.
Failed to close the file: sfx/sheep_noise.mp3
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "D:\dev\Sheepy\main.py", line 89, in move_image
    if check_position():
  File "D:\dev\Sheepy\main.py", line 66, in check_position
    play_sfx()
  File "D:\dev\Sheepy\main.py", line 84, in play_sfx
    playsound(SHEEP_SFX, False)
  File "D:\dev\Sheepy\lib\site-packages\playsound.py", line 72, in _playsoundWin
    winCommand(u'open {}'.format(sound))
  File "D:\dev\Sheepy\lib\site-packages\playsound.py", line 64, in winCommand
    raise PlaysoundException(exceptionMessage)
playsound.PlaysoundException:
    Error 263 for command:
        open sfx/sheep_noise.mp3
    Gerät ist nicht geöffnet oder wird vom MCI nicht erkannt.
```

**Comment by Ma-Ko-dev** [comment]
Hey!

This will probably fix itself with the addition of the requirements.txt you mentioned in https://github.com/Ma-Ko-dev/Sheepy/issues/1
